// No header for this class on purpose.
//
// Declaring a module (which a pod with Swift in it must) makes CocoaPods
// build an umbrella header out of every public header. These import React's
// Fabric headers, which are C++, and the umbrella is compiled as plain
// Objective-C - so the module build dies on `'atomic' file not found`.
// Nothing outside this file needs the class: React Native's generated
// provider only looks for the `Cls()` function below.

#import <React/RCTViewComponentView.h>
#import <react/renderer/components/SkyMatchGlassSpec/ComponentDescriptors.h>
#import <react/renderer/components/SkyMatchGlassSpec/Props.h>
#import <react/renderer/components/SkyMatchGlassSpec/RCTComponentViewHelpers.h>

// Generated by the compiler from SkyMatchGlass.swift, which is where the
// actual Liquid Glass lives. The pod sets DEFINES_MODULE so this exists.
// Where this header lands depends on whether the pods are built as static
// libraries (the default) or as frameworks (USE_FRAMEWORKS in the Podfile),
// and the app can be built either way.
#if __has_include(<skymatch_peripheral/skymatch_peripheral-Swift.h>)
#import <skymatch_peripheral/skymatch_peripheral-Swift.h>
#else
#import "skymatch_peripheral-Swift.h"
#endif

using namespace facebook::react;

/**
 * A pane of SwiftUI's `glassEffect(_:in:)`, to sit behind React Native
 * content. It hosts no React children: a leaf view has none of the mounting
 * rules a container has, and the caller puts it behind whatever it likes
 * with an absolute fill.
 */
@interface SkyMatchGlassView : RCTViewComponentView <RCTSkyMatchGlassViewViewProtocol>
@end

@implementation SkyMatchGlassView {
  SkyMatchGlassSurfaceHost *_surface;
}

+ (ComponentDescriptorProvider)componentDescriptorProvider
{
  return concreteComponentDescriptorProvider<SkyMatchGlassViewComponentDescriptor>();
}

- (instancetype)initWithFrame:(CGRect)frame
{
  if (self = [super initWithFrame:frame]) {
    static const auto defaultProps = std::make_shared<const SkyMatchGlassViewProps>();
    _props = defaultProps;

    _surface = [[SkyMatchGlassSurfaceHost alloc] initWithFrame:self.bounds];
    _surface.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    self.userInteractionEnabled = NO;
    [self addSubview:_surface];
  }
  return self;
}

- (void)updateProps:(Props::Shared const &)props oldProps:(Props::Shared const &)oldProps
{
  const auto &next = *std::static_pointer_cast<SkyMatchGlassViewProps const>(props);

  // A pill is written in a stylesheet as an absurd radius (999). A shape
  // takes it literally, so it is capped at half the shorter side - which is
  // exactly a pill.
  CGFloat requested = (CGFloat)next.cornerRadius;
  CGFloat limit = MIN(CGRectGetWidth(self.bounds), CGRectGetHeight(self.bounds)) / 2.0;
  CGFloat radius = requested <= 0 ? 0 : (limit > 0 ? MIN(requested, limit) : requested);
  if (_surface.cornerRadius != radius) {
    _surface.cornerRadius = radius;
  }

  [super updateProps:props oldProps:oldProps];
}

- (void)layoutSubviews
{
  [super layoutSubviews];

  // The cap above depends on the size, which isn't known when props arrive.
  const auto &current = *std::static_pointer_cast<SkyMatchGlassViewProps const>(_props);
  CGFloat requested = (CGFloat)current.cornerRadius;
  if (requested <= 0) {
    return;
  }
  CGFloat limit = MIN(CGRectGetWidth(self.bounds), CGRectGetHeight(self.bounds)) / 2.0;
  CGFloat radius = MIN(requested, limit);
  if (_surface.cornerRadius != radius) {
    _surface.cornerRadius = radius;
  }
}

@end

Class<RCTComponentViewProtocol> SkyMatchGlassViewCls(void)
{
  return SkyMatchGlassView.class;
}
